package routes

import (
	"gin-and-swaggo/controllers"

	swaggerFiles "github.com/swaggo/files"     // swagger embed files
	ginSwagger "github.com/swaggo/gin-swagger" // gin-swagger middleware

	"github.com/gin-gonic/gin"

	"gin-and-swaggo/docs" // docs is generated by Swag CLI, you have to import it.
)


func StartServer() *gin.Engine {
	router := gin.New()

	docs.SwaggerInfo.Title = "Swagger Example API OVveride"

	router.GET("/orders", controllers.GetOrders)
	router.POST("/orders", controllers.CreateOrder)

	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
	
	return router
}